### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by dunk8888** [Rodot/Gamebuino#18]
wont compile but the older bootloader will,it seems to be the gamebuin_boot.C file the one thats 23kb the one thats 22kb in the older respository works,but not sure whats going on and why its stopping it from compiling,but it says somthing about jumps 00007ffa -> 00007ffd overlaps section . text 80007800.can you sort it maybe simple fix.

**Comment by Sorunome** [comment]
The newer gcc compilers lack a flag used to make the bootloader smaller, you will either need to downgrade gcc or need some other compiling flags. Unfortunately I can't find them currently, I found them by looking at how to replace the  -fno-inline-small-functions flag (I think)

**Comment by dunk8888** [comment]
Hi thanks for the info,i was going to try downgrading avr gcc as ive got a
few older versions allready downloaded,ile give it a go and see what
happens.thanks

**Comment by dunk8888** [comment]
Thanks pal thats sorted it,ive been messing for days trying to compile
it,all i had to do is install an older version of win avr, thanks again. ;-)

**Comment by inajob** [comment]
I have faced this Issue and solved that.
I built gamebuino bootloader in below changes.

gcc version 4.9.2 (Debian 4.9.2-10) 

```
-CFLAGS = -c -g -Os -Wall -fno-inline-small-functions -fno-split-wide-types -mshort-calls -mmcu=atmega328p -DF_CPU=16000000L  '-DLED_START_FLASHES=3' '-DBAUD_RATE=115200' \
+CFLAGS = -c -g -Os -Wall -fno-split-wide-types -ffunction-sections -fdata-sections -fno-tree-scev-cprop -mrelax -mmcu=atmega328p -DF_CPU=16000000L  '-DLED_START_FLASHES=3' '-DBAUD_RATE=11
5200' \
```

```
-LINK_FLAGS =   -g -Wall -Os -fno-inline-small-functions -fno-split-wide-types -mshort-calls -mmcu=atmega328p -Wl,--relax -Wl,--gc-sections -nostartfiles -nostdlib \
+LINK_FLAGS =   -g -Wall -mmcu=atmega328p -Wl,--relax -Wl,--gc-sections -nostartfiles -nostdlib \
```

**Comment by dunk8888** [comment]
Doesnt work for me,i take it i copy and replace the two lots of lines of code to the make files? i get tones of errors declair errors mostly
