### ISSUE TITLE
Bootloader size

### ISSUE THREAD

**Issue by dunk8888** [Rodot/Gamebuino#25]
Hi whats the bootloader size? i want to use the bootloader and lcd as a neopixel controller and pick the hex files with differant sketch patterns on.Also how would i change the bmp from gamebuino to Pixel Loader for example,is it in the loader or bootloader,i think its the later.
Thanks

**Comment by Rodot** [comment]
Hi,
The bootloader is 2KB. The logo is in the loader and games, not the bootloader. Please use the [Gamebuino forum](http://gamebuino.com/forum/), thanks !
